# Ce fichier est utilise pour la gestion du CI (compile, test, ...) de GitLab

variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

# This template uses jdk12 for verifying and deploying images
image: maven:3.8.1-jdk-11


cache:
  paths:
    - .m2/repository
    - target

stages:
  - build
  - test
  - quality
  - package
  - install

compileJob:
  stage: build
  script:
    - echo "This job is build"
    - 'mvn $MAVEN_CLI_OPTS compile'

testJob:
  stage: test
  script:
    - echo "This job is test"
    - 'mvn $MAVEN_CLI_OPTS test'

#Fonctionne mais n est pas interessant 
#qualityJob:
#  stage: quality
#  image: docker:stable
#  allow_failure: true
#  services:
#    - docker:stable-dind
#  script:
#    - mkdir codequality-results
#    - docker run
#        --env CODECLIMATE_CODE="$PWD"
#        --volume "$PWD":/code
#        --volume /var/run/docker.sock:/var/run/docker.sock
#        --volume /tmp/cc:/tmp/cc
#        codeclimate/codeclimate analyze -f html > ./codequality-results/index.html
#  artifacts:
#    paths:
#      - codequality-results/

#sonar:
#  image: sonarsource/sonar-scanner-cli
#  script:
#    - sonar-scanner -Dsonar.qualitygate.wait=true
#  allow_failure: true
#  variables:
#    SONAR_PROJECT_BASE_DIR: "${CI_PROJECT_DIR}"

