
INSERT INTO trek (NAME, YEAR, LOCATION) VALUES ('TEST_NAME_1', '2019', 'TEST_LOCATION_1'); 
INSERT INTO trek (NAME, YEAR, LOCATION) VALUES ('TEST_NAME_2', '2019', 'TEST_LOCATION_2'); 

INSERT INTO day (NUMBER, TREK_ID) VALUES ('TEST_NUMBER_1', 1); 
INSERT INTO day (NUMBER, TREK_ID) VALUES ('TEST_NUMBER_2', 2); 
