
create table IF NOT EXISTS day (id bigint generated by default as identity, number varchar(255) not null, trek_id bigint, primary key (id));

create table  IF NOT EXISTS trek (id bigint generated by default as identity, location varchar(255) not null, name varchar(255) not null, year integer not null, primary key (id));

alter table day add constraint IF NOT EXISTS FKia0ili7b1146fnbua840r5vk1 foreign key (trek_id) references trek;



